language: python
python:
- 3.8
install: pip install -U tox-travis
before_script:
- export TZ=Asia/Shanghai
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  username: __token__
  password:
    # token_name: "travis"
    secure: "UsDsg+KwyBaf3RsMpEA1kJ9VTvahlIqdMtSXynya6PE+eMaEa7I7sTmWTxMGxcAnyGUqSlKYR0SkOZuSUxz+fuWttadF1sju+AMeWHM/3ibt3lwYb/96b+1hfLZmsXJ7mCnkpROVCdeUvHhfGpP198VbXrHZNLn5E2IltlYHM/rstU/qmHDgHlvZEnVdnM7Uc0MUhE3YwsDw1T/MZQ0G2Hhi0LY0V+72xKKH7i3mzjaj6oInOfNQIOGeJGsXo2W1EPGvOBBIf7JlWVug9ePwrDaGYfj8wdry2BTxuZFAEkAhaRQdVcjrgpi5BtUWYDVhSfQiAhKHlGlfmAAwFFaXGaqAIn5Rwn1p7V1DNovgKpNFbH0I/fFedVxcANBqR32vbkG3jBzVBetL5gPBgwkYmXoLZtAmKBneoK4bK/vzpRE8417962LXhIDIroqrOT9KEDhimaeY+15WNgTj8ErWPm7CfYBfGaBSiNinCyFEenZvE0lnbWZpH5ixLjaB0/FiVleqTbdie175+dCLRAd0q6xef2eHu+FteOxwZbtXQfMzeAU2NeXGzjXONopQtZSD1thBEzzsFyB43da/hUs27nkkyLKw6rC7f+rlQhx+eieoNTM+ojKtNkE9VTkojTTSzmspVgiCjojubjRhLaGXOm4B7ozknu6f5WUQs0rK1Ks="
  on:
    tags: true
    python: 3.8
