language: python
python:
- 3.8
install: pip install -U tox-travis
before_script:
- export TZ=Asia/Shanghai
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  username: __token__
  password:
    secure: gDr9mvnJ/84sGmuZZ0wxSIrWL0VZAF6EEF1x4Var5d4doZfxrGOVmX9e/zzU0qVnhJYQRFpqFXM4cnt4PiwWI3AspbrTeSGsUD135lEPH3hUd7YpKSjLqnLvHF7iPsNqsHw9YiqMZaSOckmUjbM29rbJ6ouVIhLq0WKL8tSNF3jQKalfKey6+EIjCJdtPA+TY0sEgmAX+w5MlBTxm9iz0CfxanPcEi3bipmGD1NNztywtgi4zqyrnrzge7zUx1F6NNume26NY9Y56WUwN4hiOIz0Jr7IYqXA8a+zokq/pVNEn4J4iDRQyS/NZj0qq1G+rKA94tgmfxQqhc7ouQ1qkj0zyi7cwPY9BKfbd2A/J4UK4yO78ZTG1dJjln2/uWabc3NWHBjz035GrRy6zdYwSiu5LoyoNwUbbn+0Gkwg24s0EyQz/vl02zROnJwhfv+PWpVGC8TMI5DPJ6QN9vk7z0fKB8nMK+c9PV8aawOmYaRBdHERIgqYTU8CsLqgnG8rZrfie0xbJrCjwGkpkNkO2FDkPb2dhTYjbWvbe2gCEyH8GehKBiX6oME1QRvgrn6YvIXIc6CACBOv/mktqTwLtTELJyY9UmDFlSmCUHY+YyK69eKq8rntJNpsIfAwi9uAxtayAm+QijD6NTbvkvAbnHi8u5aSULrW7dmNnDmcPa4=
  on:
    tags: true
    python: 3.8
