language: python
python:
- 3.8
install: pip install -U tox-travis
before_script:
- export TZ=Asia/Shanghai
script: tox
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  user: __token__
  password: pypi-AgENdGVzdC5weXBpLm9yZwIkNGMzZTE1YzUtMzdjYy00MzQ5LWI3YzItMWRjNTQ4MjVjNmNhAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiCpBVQmmCAyKGxBDSZqKBJ6CQjkddMvzRUI1rWGKZDP-A
  true:
    tags: true
    python: 3.8
