# Publish package on release branch if it's tagged with 'v*'

name: release & publish on master branch

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branch: master
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    name: Create Release
    runs-on: ubuntu-18.04
    env:
      JQ_ACCOUNT: "${{secrets.JQ_ACCOUNT}}"
      JQ_PASSWORD: ${{secrets.JQ_PASSWORD}}

    strategy:
      matrix:
        python-versions: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: build change log
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: test
        run: >-
          tox

      - name: build
        run: >-
          make dist

      - name: create github release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: dist/*.whl
          draft: false
          prerelease: false
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.whl
          asset_name: omega-jqadapter-kk
          tag: 1.2.1-alpha
          overwrite: true
          body: "1.2.1-alpha"
      # - name:
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
      #     skip_existing: true

      # - name: Dingtalk Robot Notify
      #   uses: leafney/dingtalk-action@v1.0.0
      #   env: 
      #     DINGTALK_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
      #     DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
      #   with:
      #     msgtype: markdown
      #     notify_when: 'success'
      #     title: Release ${{ github.ref }}
      #     text: |
      #       ## 变更历史
      #       ${{ steps.build_changelog.outputs.changelog }}            
